---
- hosts: elasticsearch
  tasks:
  # repoXplorer does not manage DB version so wipe it
  - name: Remove repoxplorer EL index
    command: curl -XDELETE "http://elasticsearch:9200/repoxplorer/"

- hosts: repoxplorer
  tasks:
  - name: Check repoxplorer version
    command: rpm -q --queryformat '%{VERSION}' repoxplorer
    register: repoxplorer_version

- hosts: install-server
  tasks:
  - block:

    - name: "Copy config file updater"
      copy:
        src: update-repoxplorer-config.py
        dest: /tmp/update-repoxplorer-config.py

    - name: "Update projects yaml file"
      command: chdir=/root/config {{ item }}
      with_items:
        - python /tmp/update-repoxplorer-config.py repoxplorer/projects.yaml
        - git add repoxplorer/projects.yaml

    - name: "Check file has changes"
      command: chdir=/root/config git --no-pager diff --name-only --staged
      register: result

    - name: "Push repoxplorer directory in the config repo"
      command: chdir=/root/config {{ item }}
      with_items:
        - git commit -m "Update repoxplorer configuration"
        - git push git+ssh://{{ fqdn }}/config master
      when: "'projects.yaml' in result.stdout"

    when: repoxplorer_version.stdout == '0.7.2'

- hosts: repoxplorer
  tasks:
  - block:

    - name: "Copy config file updater"
      copy:
        src: update-repoxplorer-config.py
        dest: /tmp/update-repoxplorer-config.py

    - name: "Update projects yaml file"
      command: python /tmp/update-repoxplorer-config.py /etc/repoxplorer/projects.yaml

    when: repoxplorer_version.stdout == '0.7.2'

  - name: "Restart repoxplorer indexer"
    service: name=repoxplorer state=restarted
