---
- hosts: elasticsearch
  tasks:
  # repoXplorer does not manage DB version so wipe it
  - name: Remove repoxplorer EL index
    command: curl -XDELETE "http://elasticsearch:9200/repoxplorer/"

- hosts: repoxplorer
  tasks:
  - name: Check repoxplorer version
    command: rpm -q --queryformat '%{VERSION}' repoxplorer
    register: repoxplorer_version

- hosts: install-server
  tasks:
  - block:

    - name: "Remove repoXplorer previous configuration"
      command: chdir=/root/config {{ item }}
      with_items:
        - rm -f repoxplorer/*
        - touch repoxplorer/.placeholder
        - git add repoxplorer

    - name: "Push repoxplorer directory in the config repo"
      command: chdir=/root/config {{ item }}
      with_items:
        - git commit -m "Update repoxplorer configuration"
        - git push git+ssh://{{ fqdn }}/config master

    when: repoxplorer_version.stdout == '0.8.0'

- hosts: repoxplorer
  tasks:
  - block:

    - name: "Remove old index files"
      command: rm -f /etc/repoxplorer/projects.yaml /etc/repoxplorer/idents.yaml

    when: repoxplorer_version.stdout == '0.8.0'

  - name: "Restart repoxplorer indexer"
    service: name=repoxplorer state=restarted
