---
- hosts: elasticsearch
  tasks:
  # repoXplorer does not manage DB version so wipe it
  - name: Remove repoxplorer EL index
    command: curl -XDELETE "http://elasticsearch:9200/repoxplorer/"

- hosts: install-server
  tasks:
  - name: Get SF version
    shell: cat /etc/sf-release
    register: sf_release

- hosts: install-server
  tasks:
  - block:

    - name: "Remove repoXplorer previous configuration"
      shell: chdir=/root/config {{ item }}
      with_items:
        - git rm -r repoxplorer
        - mkdir repoxplorer
        - echo "Here to place custom configuration for repoXplorer." > repoxplorer/README
        - git add repoxplorer

    - name: "Push repoxplorer directory in the config repo"
      command: chdir=/root/config {{ item }}
      with_items:
        - git commit -m "Update repoxplorer configuration"
        - git push git+ssh://{{ fqdn }}/config master

    when: sf_release.stdout == '2.5.0'

- hosts: repoxplorer
  tasks:
  - block:

    - name: "Remove old index files"
      command: rm -f /etc/repoxplorer/projects.yaml /etc/repoxplorer/idents.yaml

    when: sf_release.stdout == '2.5.0'

  - name: "Restart repoxplorer indexer"
    service: name=repoxplorer state=restarted
