---
- hosts: install-server
  pre_tasks:
  - include: tasks/remove_puppet.yaml
  tasks:
  - include: tasks/fetchupstream.yml
  - include: tasks/gerritbot_configrepo_import.yml
  - include: tasks/gerrit_configrepo_import.yml
  - include: tasks/dashboard_configrepo_import.yml
  - include: tasks/zuul_layout_namechange.yml
  - include: tasks/sf_jjb_namechange.yml
  - include: tasks/policy_configrepo.yml
  - include: tasks/job_api_configrepo.yml
  - include: tasks/agent_api_configrepo.yml
  - include: tasks/resources_configrepo.yml
  - include: tasks/gerrit_default_jenkins_user.yml
  - include: tasks/nodes_image_update.yml
  - include: tasks/repoxplorer_configrepo.yml

- hosts: zuul
  tasks:
  - service: name=zuul state=stopped

- hosts: nodepool
  tasks:
  # Ignore errors when the service is not started...
  - service: name=nodepool state=stopped
    ignore_errors: yes

- hosts: install-server
  tasks:
  - include: tasks/update_configrepo.yaml
  - name: "Check for new nodepool config repo"
    stat: path=/root/config/nodepool/elements
    register: nodepool_elements
  - block:
    - copy: src=sf-nodepool-conf-migrator.py dest=/root
    - name: "Migrate nodepool configuration"
      command: chdir=/root/config {{ item }}
      with_items:
        - rsync -a {{install_path}}/softwarefactory/usr/share/sf-config/config-repo/nodepool/elements/ nodepool/elements/
        - python /root/sf-nodepool-conf-migrator.py
        - git add nodepool/nodepool.yaml nodepool/elements nodepool/scripts
        - git commit -a -m "Update nodepool configuration"
        - git push git+ssh://gerrit/config master
    - file: path=/root/sf-nodepool-conf-migrator.py state=absent

    when: nodepool_elements.stat.exists == false

- hosts: all
  tasks:
  - include: tasks/clean_root_crontab.yml
  - include: tasks/stopsfservices.yml

- hosts: all
  tasks:
  - name: Synchronize FS with eDeploy
    command: edeploy upgrade {{ version }}
