---
- hosts: all
  tasks:
  - include: tasks/bootloader.yml
  - shell: /usr/share/sf-config/scripts/sf-update-uid-gid.py 2>&1 | tee -a /var/log/sf_ids_update.log
  # Remove unused users
  - user: name=murmur state=absent
  - group: name=murmur state=absent

- hosts: install-server
  tasks:
  # 2.0.0: Remove hosts.yaml hiera
  - file: path=/etc/software-factory/hosts.yaml state=absent
  # 2.3.0: Import mysql_root_password
  - file: path=/var/lib/software-factory/bootstrap-data state=directory mode=0700 owner=root group=root
  - command: grep ^mysql_root_password /var/lib/software-factory/bootstrap-data/secrets.yaml
    register: new_password
    ignore_errors: yes
  - command: awk '/creds_mysql_root_pwd/ { print $2 }' /etc/software-factory/sfcreds.yaml
    register: mysql_root_password
    when: new_password.rc != 0
  - command: /usr/share/sf-config/scripts/hieraedit.py --yaml /var/lib/software-factory/bootstrap-data/secrets.yaml mysql_root_password {{ mysql_root_password.stdout }}
    when: new_password.rc != 0
  # 2.3.0: Remove gerrit.yaml hiera
  - stat: path=/etc/software-factory/gerrit.yaml
    register: gerrit_hiera
  - command: awk '/gerrit_heap_limit/ { print $2 }' /etc/software-factory/gerrit.yaml
    register: heap_limit
    when: gerrit_hiera.stat.exists == True
  - command: /usr/share/sf-config/scripts/hieraedit.py --yaml /etc/software-factory/custom-vars.yaml gerrit_heap_limit {{ heap_limit.stdout }}
    when: gerrit_hiera.stat.exists == True
  - file: path=/etc/software-factory/gerrit.yaml state=absent
  # 2.3.0: Remove jenkins.yaml hiera
  - stat: path=/etc/software-factory/jenkins.yaml
    register: jenkins_hiera
  - command: awk '/jenkins_heap_limit/ { print $2 }' /etc/software-factory/jenkins.yaml
    register: heap_limit
    when: jenkins_hiera.stat.exists == True
  - command: /usr/share/sf-config/scripts/hieraedit.py --yaml /etc/software-factory/custom-vars.yaml jenkins_heap_limit {{ heap_limit.stdout }}
    when: jenkins_hiera.stat.exists == True
  - file: path=/etc/software-factory/jenkins.yaml state=absent
  # 2.3.0: Remove sf_version.yaml hiera
  - file: path=/etc/software-factory/sf_version.yaml state=absent
  # 2.3.0: Move sshkey to /var/lib/software-factory/bootstrap-data/ssh_keys
  - file: path=/var/lib/software-factory/bootstrap-data/ssh_keys state=directory mode=0700 owner=root group=root
  - shell: "[ -f /root/sf-bootstrap-data/ssh_keys/gerrit_service_rsa ] && mv /root/sf-bootstrap-data/ssh_keys/gerrit_*_rsa* /var/lib/software-factory/bootstrap-data/ssh_keys/ || true"
  - shell: "[ -f /root/sf-bootstrap-data/ssh_keys/jenkins_rsa ] && mv /root/sf-bootstrap-data/ssh_keys/jenkins_rsa* /var/lib/software-factory/bootstrap-data/ssh_keys/ || true"
  - shell: "[ -f /root/sf-bootstrap-data/ssh_keys/service_rsa ] && mv /root/sf-bootstrap-data/ssh_keys/service_rsa* /var/lib/software-factory/bootstrap-data/ssh_keys/ || true"
  - file: path=/var/lib/software-factory/bootstrap-data/certs state=directory mode=0700 owner=root group=root
  - shell: "[ -f /root/sf-bootstrap-data/certs/localCA.pem ] && mv /root/sf-bootstrap-data/certs/localCA* /var/lib/software-factory/bootstrap-data/certs/ || true"
  - file: path=/etc/software-factory/sfcreds.yaml state=absent
  - file: path=/etc/software-factory/_arch.yaml state=absent
  - file: path=/root/sf-bootstrap-data state=absent

- hosts: gerrit
  tasks:
  - name: "Check for previous install"
    stat: path=/home/gerrit/site_path
    register: gerrit_home

  - block:
    # 2.4.0: switch to packaged version
    - name: "Move config file to /etc"
      command: rsync -a /home/gerrit/site_path/etc/ /etc/gerrit/

    - name: "Move logs to /var/log"
      command: rsync -a /home/gerrit/site_path/logs/ /var/log/gerrit/

    - name: "Move data to /var/lib"
      command: rsync -a /home/gerrit/site_path/cache /home/gerrit/site_path/data /home/gerrit/site_path/index /home/gerrit/site_path/git /home/gerrit/site_path/static /home/gerrit/site_path/tmp /var/lib/gerrit/

    - name: "Move .ssh to new home directory"
      command: rsync -a /home/gerrit/.ssh/ /var/lib/gerrit/.ssh/

    - name: "Fix keypath in .ssh/config"
      command: sed -i "s#/home/gerrit/#/var/lib/gerrit/#" /var/lib/gerrit/.ssh/config

    - name: "Remove known_hosts symlink"
      file: path=/var/lib/gerrit/.ssh/known_hosts state=absent

    - name: "Install real known_hosts"
      command: mv /var/lib/gerrit/.ssh/known_hosts_gerrit /var/lib/gerrit/.ssh/known_hosts

    - name: "Archive previous gerrit tree"
      command: mv /home/gerrit /home/gerrit.old
    when: gerrit_home.stat.exists == True

- hosts: managesf
  tasks:
  # 2.2.7: managesf is running with its own user
  - name: Make sure /var/log/managesf is owned by managesf
    command: chown -R 949:949 /var/log/managesf

- hosts: all
  tasks:
  - name: systemctl daemon-reload
    shell: systemctl daemon-reload

- hosts: jenkins
  tasks:
  - name: Be sure Jenkins master executors amount is 1
    replace: dest=/var/lib/jenkins/config.xml regexp='<numExecutors>.*</numExecutors>' replace='<numExecutors>1</numExecutors>'

- hosts: install-server
  tasks:
  # /var/log/software-factory only exists after 2.2.7
  - name: Make sure /var/log/software-factory exists
    file: path=/var/log/software-factory state=directory mode=0700
  - name: Restart the configuration script
    shell: sfconfig.py --skip-install &>> /var/log/software-factory/upgrade.log
