---
- hosts: install-server
  pre_tasks:
  - include: tasks/remove_puppet.yaml
  tasks:
  - name: "Check for hieraedit"
    stat: path=/usr/share/sf-config/scripts/hieraedit.py
    register: hieraedit
  - name: "Check for scripts directory"
    file: path=/usr/share/sf-config/scripts state=directory
    when: hieraedit.stat.exists == False
  - name: "Copy hieraedit from 2.4"
    copy: src=/usr/local/bin/hieraedit.py dest=/usr/share/sf-config/scripts/hieraedit.py remote_src=true mode=0755
    when: hieraedit.stat.exists == False
  - include: tasks/fetchupstream.yml
  - include: tasks/gerritbot_configrepo_import.yml
  - include: tasks/gerrit_configrepo_import.yml
  - include: tasks/dashboard_configrepo_import.yml
  - include: tasks/zuul_layout_namechange.yml
  - include: tasks/sf_jjb_namechange.yml
  - include: tasks/policy_configrepo.yml
  - include: tasks/job_api_configrepo.yml
  - include: tasks/agent_api_configrepo.yml
  - include: tasks/resources_configrepo.yml
  - include: tasks/gerrit_default_jenkins_user.yml
  - include: tasks/nodes_image_update.yml
  - include: tasks/repoxplorer_configrepo.yml

- hosts: zuul
  tasks:
  - service: name=zuul state=stopped

- hosts: nodepool
  tasks:
  # Ignore errors when the service is not started...
  - service: name=nodepool state=stopped
    ignore_errors: yes

- hosts: install-server
  tasks:
  - include: tasks/update_configrepo.yaml
  - name: "Check for new nodepool config repo"
    stat: path=/root/config/nodepool/elements
    register: nodepool_elements
  - block:
    - copy: src=sf-nodepool-conf-migrator.py dest=/root
    - name: "Migrate nodepool configuration"
      command: chdir=/root/config {{ item }}
      with_items:
        - rsync -a {{install_path}}/softwarefactory/usr/share/sf-config/config-repo/nodepool/elements/ nodepool/elements/
        - python /root/sf-nodepool-conf-migrator.py
        - git add nodepool/nodepool.yaml nodepool/elements nodepool/scripts
        - git commit -a -m "Update nodepool configuration"
        - git push git+ssh://gerrit/config master
    - file: path=/root/sf-nodepool-conf-migrator.py state=absent
    when: nodepool_elements.stat.exists == false

  # Update conf
  - include_vars: /etc/software-factory/sfconfig.yaml
  - name: "Update config-repo files"
    template:
      src: "{{ item.src }}"
      dest: "/root/config/{{ item.dest }}"
    register: config_repo_status
    with_items:
      - { src: "/usr/share/sf-config/templates/_macros.yaml.j2", dest: jobs-zuul/_macros.yaml }
      - { src: "/usr/share/sf-config/config-repo/jobs-zuul/_config.yaml",  dest: jobs-zuul/_macros.yaml }
      - { src: "/usr/share/sf-config/templates/_default_jobs.yaml.j2", dest: jobs/_default_jobs.yaml }
      - { src: "/usr/share/sf-config/config-repo/zuul/_layout.yaml", dest: zuul/_layout.yaml }
  - name: "Push config-repo updates"
    command: chdir=/root/config {{ item }}
    with_items:
      - git add jobs-zuul/_macros.yaml
      - git commit -m "Update default configuration"
      - git push git+ssh://{{ fqdn }}/config master
    when: config_repo_status|changed


- hosts: all
  tasks:
  - include: tasks/clean_root_crontab.yml
  - include: tasks/stopsfservices.yml

- hosts: all
  tasks:
  - name: Synchronize FS with eDeploy
    command: edeploy upgrade {{ version }}
