#!/bin/sh -ex
useradd -m -d /home/jenkins jenkins
mkdir -m 0700 /home/jenkins/.ssh
cp /tmp/in_target.d/id_rsa.pub /home/jenkins/.ssh/authorized_keys
chmod 0600 /home/jenkins/.ssh/authorized_keys
chown -R jenkins:jenkins /home/jenkins
echo -e "Defaults    !requiretty\njenkins ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/jenkins
