---
# Use 0751 to let apache access /var/lib/zuul/git
- include: /etc/ansible/tasks/create_user.yml user_name=zuul ssh_key=jenkins_rsa home_dir_mode=0751

- name: Apply selinux port labelling
  seport:
      ports: "{{ zuul_port }}"
      proto: tcp
      setype: http_port_t
      state: present
  when:
      - selinuxenabled

- name: Setup apache site zuul.conf
  template: src=zuul.site.j2 dest=/etc/httpd/conf.d/zuul.conf mode=0444
  notify: apache reload

- name: Create /var/www/zuul
  file: path=/var/www/zuul state=directory

- name: Symlink zuul image
  file: src=/usr/share/javascript/zuul/images/ dest=/var/www/zuul/images state=link

- name: Symlink zuul static assets
  file: src=/usr/share/javascript/zuul/ dest=/var/www/static/zuul state=link

- name: Install index.html for zuul
  copy:
    src: zuul.index.html
    dest: /var/www/zuul/index.html
    mode: 0444

- name: "Copy logging configuration"
  template: src={{ item }}.j2 dest=/etc/zuul/{{ item }}
  with_items:
    - logging.conf
    - gearman-logging.conf
    - merger-logging.conf

- name: "Setup sysconfig"
  template: src=sysconfig.j2 dest=/etc/sysconfig/zuul
  notify: restart zuul

- name: "Setup configuration"
  template: src=zuul.conf.j2 dest=/etc/zuul/zuul.conf mode=0440 group=zuul
  notify: restart zuul

- name: Start service
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ zuul_services }}"

- name: "Copy gearman-check script"
  copy: src=gearman-check dest=/usr/local/bin/gearman-check mode=0555
  when: "'zuul' in zuul_services"

- name: "Setup gearman-check cron"
  cron: name=gearman-check-cron job=/usr/local/bin/gearman-check minute=0 hour=0
  when: "'zuul' in zuul_services"
