---
galaxy_info:
  description: Firehose service
  company: Red Hat
  license: Apache
  min_ansible_version: 1.9
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags:
    - software-factory
dependencies:
  - role: sf-mosquitto
  - { role: 'sf-germqtt', when: '"gerrit" in roles' }
  - { role: 'sf-ochlero', when: ('zuul' in roles) or ('nodepool' in roles) }
