diskimages: []
#  - name: dib-centos-7
#    elements:
#      - centos-minimal
#      - nodepool-minimal
#      - sf-zuul-worker
#    env-vars:
#      DIB_CHECKSUM: '1'

labels: []
#  - name: centos-7
#    image: centos-7
#    min-ready: 1
#    providers:
#      - name: default

providers: []
#  - name: default
#    cloud: default
#    clean-floating-ips: true
#    image-type: raw
#    max-servers: 10
#    boot-timeout: 120
#    pool: nova
#    rate: 10.0
#    networks:
#      - name: slave-net-name
#    images:
#      - name: centos-7
#        diskimage: dib-centos-7
#        username: jenkins
#        min-ram: 1024
