diskimages: []
#  - name: dib-centos-7
#    elements:
#      - centos-minimal
#      - nodepool-minimal
#      - sf-zuul-worker
#      - rpm-factory
#    env-vars:
#      DIB_CHECKSUM: '1'

labels: []
#  - name: centos-7
#    image: centos-7
#    min-ready: 1
#    providers:
#      - name: default

providers: []
#- boot-timeout: 120
#  clean-floating-ips: true
#  cloud: default
#  image-type: raw
#  images:
#    - name: centos-7
#      diskimage: dib-centos-7
#      username: centos
#      min-ram: 4096
#  networks:
#    - name: sf-integration-slave_net-77ftqqzwwmzb
#  max-servers: 10
#  name: default
#  pool: nova
#  rate: 10.0
