---
- name: "Set Elasticsearch host"
  replace:
    dest: /etc/repoxplorer/config.py
    regexp: "^elasticsearch_host =.*$"
    replace: "elasticsearch_host = 'elasticsearch'"

- name: "Set default index file in repoxplorer conf"
  replace:
    dest: /etc/repoxplorer/config.py
    regexp: "^db_default_file =.*$"
    replace: "db_default_file = '/etc/repoxplorer/default.yaml'"

- name: "Install default index file for repoxplorer"
  template:
    src: default.yaml.j2
    dest: /etc/repoxplorer/default.yaml
    force: no

- name: "Remove index.yaml example definition"
  file:
    path: /etc/repoxplorer/index.yaml
    state: absent

- name: "Install top menu"
  lineinfile:
    dest: /usr/share/repoxplorer/templates/layout.html
    insertafter: '<%def name="javascript()">'
    line: '    <script src="/static/js/topmenu.js"></script>'

- name: "Install resources2repoxplorer"
  copy:
    src: "{{ item.name }}"
    dest: /usr/local/bin/
    mode: 0755
  with_items:
    - { name: resources2repoxplorer.py }

- name: Start service
  systemd:
    name: "{{ item }}"
    state: started
    daemon_reload: yes
    enabled: yes
  with_items:
    - repoxplorer-webui
    - repoxplorer

- name: "Install Apache gateway rule for repoxplorer"
  template:
    src: gateway-repoxplorer.conf.j2
    dest: /etc/httpd/conf.d/gateway-repoxplorer.conf
