---
- name: "Set Elasticsearch host"
  replace:
    dest: /etc/repoxplorer/config.py
    regexp: "^elasticsearch_host =.*$"
    replace: "elasticsearch_host = 'elasticsearch'"

- name: Start service
  systemd:
    name: "{{ item }}"
    state: started
    daemon_reload: yes
    enabled: yes
  with_items:
    - repoxplorer-webui
    - repoxplorer

- name: "Install Apache gateway rule for repoxplorer"
  template:
    src: gateway-repoxplorer.conf.j2
    dest: /etc/httpd/conf.d/gateway-repoxplorer.conf
