---
- file: path=/var/lib/software-factory/repoxplorer_config state=touch

- name: "Check local repoxplorer config"
  command: cat /var/lib/software-factory/repoxplorer_config
  register: localconfig

- name: "Check upstream repoxplorer config"
  command: chdir=/root/config git log --oneline repoxplorer/
  register: upstreamconfig

- name: "Update local repoxplorer configuration files"
  when: localconfig.stdout != upstreamconfig.stdout
  copy:
    src: "{{ item }}"
    dest: "/etc/repoxplorer/"
  with_fileglob:
    - "/root/config/repoxplorer/*"

- name: "Write config repo sha1 matching current repoxplorer configuration"
  copy: content="{{ upstreamconfig.stdout }}" dest=/var/lib/software-factory/repoxplorer_config
  when: localconfig.stdout != upstreamconfig.stdout

- name: "Update default repoxplorer index file from SF resources"
  command: /usr/local/bin/resources2repoxplorer.py apply
