---
- include: /etc/ansible/tasks/create_user.yml user_name=jenkins ssh_key=jenkins_rsa

- name: Create working directories
  file:
      path: "{{ item.name }}"
      state: directory
      owner: jenkins
      group: jenkins
      mode: "{{ item.mode | default(0755) }}"
  with_items:
    - {name: /etc/jenkins_jobs, mode: '0500'}
    - {name: /usr/local/share/sf-jenkins-slave-tools}
    - {name: /var/cache/jenkins}
    - {name: /var/lib/jenkins}
    - {name: /var/lib/jenkins/defconf, mode: '0500'}
    - {name: /var/lib/jenkins/plugins}
    - {name: /var/lib/jenkins/init.groovy.d}

- name: Install templates for root user
  template:
      src: "{{ item.name }}.j2"
      dest: "{{item.dest}}/{{ item.name }}"
      owner: root
      group: root
      mode: "{{ item.mode | default(0444) }}"
  with_items:
      - {name: jenkins-remove-offline-node.sh, dest: /etc/cron.daily, mode: '0555'}
      - {name: nodepool.yaml, dest: /var/lib/jenkins/defconf}
      - {name: resources.sh, dest: /usr/local/bin, mode: '0555'}
      - {name: zuul.conf, dest: /var/lib/jenkins/defconf}

- name: Install templates for jenkins user
  template:
      src: "{{ item.name }}.j2"
      dest: "{{item.dest | default('/var/lib/jenkins') }}/{{ item.name }}"
      owner: jenkins
      group: jenkins
      mode: "{{ item.mode | default(0444) }}"
  with_items:
      - {name: hudson.plugins.gearman.GearmanPluginConfig.xml}
      - {name: hudson.plugins.git.GitSCM.xml}
      - {name: jenkins.model.JenkinsLocationConfiguration.xml}
      - {name: jenkins_jobs.ini, dest: /etc/jenkins_jobs, mode: '0400'}

- name: Install files for root user
  template:
      src: "{{ item.name }}.j2"
      dest: "{{item.dest}}/{{ item.name }}"
      owner: root
      group: root
      mode: "{{ item.mode | default(0444) }}"
  notify:
      - apache reload
  with_items:
      - {name: jenkins, dest: /etc/sudoers.d, mode: '0440'}
      - {name: jenkins.conf, dest: /etc/httpd/conf.d}
      - {name: ports.conf, dest: /etc/httpd/conf.d}
      - {name: remove-offline-node.groovy, dest: /var/lib/jenkins/}
      - {name: wait4jenkins, dest: /usr/libexec, mode: '0555'}

- name: Install files for jenkins user
  copy:
      src: "{{ item.name }}"
      dest: "/var/lib/jenkins/{{ item.name }}"
      owner: jenkins
      group: jenkins
      mode: "{{ item.mode | default(0444) }}"
      force: "{{ item.force | default('yes') }}"
  with_items:
      - {name: config.xml, mode: '0644', force: no}
      - {name: credentials.xml, mode: '0644', force: no}
      - {name: hudson.tasks.Mailer.xml}
      - {name: org.codefirst.SimpleThemeDecorator.xml}
      - {name: org.jenkinsci.main.modules.sshd.SSHD.xml}
      - {name: org.jenkinsci.plugins.ZMQEventPublisher.HudsonNotificationProperty.xml}

- name: Install init script that sets SF service credentials in Jenkins secrets store
  template:
      src: service_user_credentials.groovy.j2
      dest: /var/lib/jenkins/init.groovy.d/service_user_credentials.groovy
      owner: jenkins
      group: jenkins
      mode: 0444
      force: yes

- name: Manage jenkins user password for apache
  htpasswd:
      path: /etc/httpd/htpasswd
      name: jenkins
      password: "{{ jenkins_password }}"

- name: Apply selinux port labelling
  seport:
      ports: "{{ item }}"
      proto: tcp
      setype: http_port_t
      state: present
  with_items: ["{{ jenkins_http_port}}", "{{ jenkins_api_port }}"]
  when:
      - selinuxenabled

- name: Install service file
  template:
      src: jenkins.service.j2
      dest: /lib/systemd/system/jenkins.service
      owner: root
      group: root
      mode: 0644

- name: Start service
  systemd:
      name: jenkins
      state: started
      daemon_reload: yes
      enabled: yes
