mariadb-server:
libvirt-daemon-kvm:
rabbitmq-server:
openvswitch:
python-openstackclient:
puppet:
qemu-img-ev:
sos:
boost-program-options:
galera:
mariadb-server-galera:
memcached:
python-urwid:
python-configshell:
openstack-nova-placement-api:
targetcli:
python-ethtool:
openstack-packstack:
openstack-cinder:
openstack-dashboard:
openstack-glance:
openstack-heat-api:
openstack-heat-common:
openstack-heat-engine:
openstack-keystone:
openstack-neutron:
openstack-neutron-common:
openstack-neutron-metering-agent:
openstack-neutron-ml2:
openstack-neutron-openvswitch:
openstack-nova-api:
openstack-nova-cert:
openstack-nova-common:
openstack-nova-compute:
openstack-nova-conductor:
openstack-nova-console:
openstack-nova-novncproxy:
openstack-nova-scheduler:
openstack-packstack:
openstack-selinux:
openstack-swift:
openstack-swift-account:
openstack-swift-container:
openstack-swift-object:
openstack-swift-plugin-swift3:
openstack-swift-proxy:
openstack-utils:

