---
- name: "Add the grafana RPM repository"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgkey: "{{ item.gpgkey }}"
    gpgcheck: "{{ item.gpgcheck }}"
  with_items:
      - {name: "{{ grafana_repo_name }}",
         description: "{{ grafana_repo_desc }}",
         baseurl: "{{ grafana_repo_url }}",
         gpgkey: "{{ grafana_repo_gpgkey }}",
         gpgcheck: "{{ grafana_repo_gpgcheck }}"}
      - {name: "{{ influxdb_repo_name }}",
         description: "{{ influxdb_repo_desc }}",
         baseurl: "{{ influxdb_repo_url }}",
         gpgkey: "{{ influxdb_repo_gpgkey }}",
         gpgcheck: "{{ influxdb_repo_gpgcheck }}"}

- name: "Install package"
  yum:
    name: grafana
    state: present
    disablerepo: "*"
    enablerepo: "{{ item.enablerepo }}"
  with_items:
      - {name: grafana, enablerepo: "{{ grafana_repo_name }}"}
      - {name: influxdb, enablerepo: "{{ influxdb_repo_name }}"}
      - {name: telegraf, enablerepo: "{{ influxdb_repo_name }}"}
      - {name: collectd, enablerepo: sfmaster}
