---
- name: Hash admin password
  shell: python <<<"{{hash_code}}'{{authentication.admin_password}}'{{hash_code_end}}"
  register: admin_password_hashed

- name: Hash service user password
  shell: python <<<"{{hash_code}}'{{sf_service_user_password}}'{{hash_code_end}}"
  register: service_user_password_hashed

- name: Install cauth config.py
  template:
      src: templates/config.py.j2
      dest: /etc/cauth/config.py
      mode: 0444
  notify: apache reload

- name: Copy app.wsgi
  copy: src=app.wsgi dest=/var/www/cauth/app.wsgi

- name: Install login.html
  template: src=login.html.j2 dest=/var/lib/cauth/templates/login.html

- name: Create httpd content
  file:
    src: /var/lib/cauth/templates
    dest: /var/www/cauth/templates
    state: link

- name: Install auth site
  copy:
    src: files/cauth.site
    dest: /etc/httpd/conf.d/cauth.conf

- name: Install cauth private key
  copy:
    content: "{{ cauth_privkey }}"
    dest: /var/lib/cauth/keys/privkey.pem
    owner: root
    group: apache
    mode: 0440
    setype: httpd_sys_content_t
