---
- name: Hash admin password
  shell: python <<<"{{hash_code}}'{{authentication.admin_password}}'{{hash_code_end}}"
  register: admin_password_hashed

- name: Hash service user password
  shell: python <<<"{{hash_code}}'{{sf_service_user_password}}'{{hash_code_end}}"
  register: service_user_password_hashed

- name: Install cauth config files
  template:
      src: "{{ item.name }}.j2"
      dest: "{{ item.dest }}/{{ item.name }}"
      mode: 0444
      owner: apache
      group: apache
  notify: apache reload
  with_items:
      - {name: config.py, dest: /etc/cauth}
      - {name: login.html, dest: /etc/cauth/templates}

- name: Install cauth files
  copy:
      src: "{{ item.name }}"
      dest: "{{ item.dest }}/{{ item.name }}"
  notify: apache reload
  with_items:
      - {name: cauth.site, dest: /etc/httpd/conf.d/}
      - {name: app.wsgi, dest: /var/www/cauth/}

- name: Install cauth private key
  copy:
      content: "{{ cauth_privkey }}"
      dest: /var/lib/cauth/keys/privkey.pem
      owner: root
      group: apache
      mode: 0440
      setype: httpd_sys_content_t
