---
- name: Create user
  include: "{{ sf_tasks_dir }}/create_user.yml user_name=umurmurd"

- name: Install config file
  template:
    src: umurmurd.conf.j2
    dest: /etc/umurmurd/umurmurd.conf
    owner: root
    group: umurmurd
    mode: 0440
  notify: restart umurmurd
