---
- include: "{{ sf_tasks_dir }}/create_user.yml user_name=managesf ssh_key=service_rsa"

- name: "Create config directory"
  file: path=/etc/managesf state=directory mode=0750 group=managesf

- name: "Copy ssh keys"
  copy:
    content: "{{ item.content }}"
    dest: "/var/lib/managesf/.ssh/{{ item.name }}"
    mode: "{{ item.mode }}"
    owner: managesf
    group: managesf
  with_items:
    - {content: "{{ gerrit_admin_rsa }}", name: "gerrit_admin_rsa", mode: "0400"}
    - {content: "{{ gerrit_admin_rsa_pub }}", name: "gerrit_admin_rsa.pub", mode: "0444"}
    - {content: "{{ jenkins_rsa }}", name: "jenkins_rsa", mode: "0400"}
    - {content: "{{ jenkins_rsa_pub }}", name: "jenkins_rsa.pub", mode: "0444"}
  no_log: True

- name: "ensure managesf_htpasswd is present"
  file: path=/etc/httpd/managesf_htpasswd state=touch mode=0640 owner=managesf group=apache

- name: "Setup config.py"
  template: src=config.py.j2 dest=/etc/managesf/config.py group=managesf mode=0440
  notify: [restart managesf]

- name: Start service
  systemd:
      name: managesf
      state: started
      daemon_reload: yes
      enabled: yes
