---
# * Submit and wait config repo change
# * Check for SUCCESS in config-update post job log
- hosts: install-server
  tasks:
    - name: Submit and approve config change
      command: chdir={{ config_path }} /usr/share/sf-config/scripts/submit_and_wait.py --approve
      register: submit_status
      ignore_errors: true

    - command: chdir={{ config_path }} cat .git/refs/heads/master
      register: commitsha

- hosts: jenkins
  tasks:
    - name: Check for config-update post job
      wait_for:
        path: "{{ config_update_log }}"
        search_regex: "{{ hostvars[groups['install-server'][0]]['commitsha'].stdout }}"
        timeout: 120

    - name: Check for SUCCESS config-update post job
      wait_for:
        path: "{{ config_update_log }}"
        search_regex: "SUCCESS"
