---
- name: "Install package"
  yum:
    name: "python-log2gearman-client"
    state: present
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"
