---
- name: "Install log gearman client configuration"
  template: src=templates/jenkins-log-client.yaml.j2 dest=/etc/log-gearman-client/config.yml owner=joblogsclient group=joblogsclient
  register: config

- name: "Start service"
  systemd:
      name: log-gearman-client
      state: started
      daemon_reload: yes
      enabled: yes

- name: "Restart log gearman client if needed"
  service: name=log-gearman-client state=restarted
  when: config|changed
