role_actions:
  - install
  - setup

grafana_http_port: 3000
grafana_internal_url: "http://localhost:{{ grafana_http_port }}/"

grafana_repo_name: grafana
grafana_repo_desc: Grafana repository
grafana_repo_url: https://packagecloud.io/grafana/stable/el/7/x86_64
grafana_repo_gpgkey: https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
grafana_repo_gpgcheck: 1

grafana_database_type: mysql
grafana_mysql_host: mysql.example.com
grafana_mysql_port: 3306
grafana_mysql_db: grafana
grafana_mysql_user: grafana
grafana_mysql_password: CHANGE_ME

grafana_server_http_port: 3000
grafana_server_root_url: "{{ gateway_url }}/grafana/"
grafana_users_allow_sign_up: false
grafana_auth_anonymous_enabled: true
grafana_auth_anonymous_org_role: Viewer
grafana_auth_proxy_enabled: true
grafana_auth_proxy_header_name: X-Forwarded-User
grafana_auth_basic_enabled: false
